// Self-contained icon system backed by lucide-react. Material-Symbol-style names
// are mapped to Lucide components so the app keeps using semantic names with no
// external icon font/CDN. Ported from the Vite app.
import {
  Activity, AlertCircle, AlignLeft, Apple, ArrowLeft, ArrowRight, ArrowUpDown, AudioLines,
  Award, BadgeCheck, Bell, Bookmark, BookmarkCheck, BookmarkX, BookOpen, Box, Boxes, Brain,
  Bug, Building2, Calculator, Calendar, Camera, Check, CheckCircle2, ChevronDown, ChevronRight,
  Clapperboard, Code, Compass, CreditCard, Download, ExternalLink, Eye, EyeOff, FileCheck, Film,
  Flame, FlaskConical, FolderOpen, Gauge, Gem, Globe, GraduationCap, Hand, Headset, Heart, Home,
  Image as ImageIcon, Infinity as InfinityIcon, Languages, Layers, LayoutDashboard, LayoutGrid,
  LineChart, Lock, LogOut, Mail, MapPin, Menu, MessageCircle, Mic, MicVocal, Minus, MonitorPlay,
  Music, Network, Package, Palette, PenLine, PenTool, Pencil, Plus, Puzzle, Receipt, ReceiptText,
  RefreshCw, Rocket, RotateCcw, Rss, Save, Search, SearchX, Send, Settings, Shapes, Shield,
  ShieldCheck, Shirt, ShoppingBag, ShoppingCart, Sigma, SlidersHorizontal, Smartphone, Smile,
  SpellCheck, Star, StarHalf, Store, Sun, Terminal, Trash2, TrendingDown, TrendingUp, Upload,
  UploadCloud, User, UserCog, UserMinus, UserPlus, UserX, Users, Video, Wallet, Wand2, Webhook,
  Workflow, X, Zap,
  Clock, LogIn, QrCode, Copy, Landmark, TimerOff, LockOpen, MailCheck, Key, KeyRound, FileText,
  GitBranch, Flag, Circle, History, XCircle, MonitorSmartphone,
  type LucideIcon,
} from "lucide-react";

const MAP: Record<string, LucideIcon> = {
  add: Plus,
  add_shopping_cart: ShoppingCart,
  all_inclusive: InfinityIcon,
  animation: Film,
  api: Webhook,
  apple: Apple,
  apps: LayoutGrid,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Wand2,
  auto_awesome_motion: Wand2,
  autorenew: RefreshCw,
  bolt: Zap,
  bookmark: Bookmark,
  bookmark_added: BookmarkCheck,
  bookmark_border: Bookmark,
  bookmark_remove: BookmarkX,
  bug_report: Bug,
  calculate: Calculator,
  calendar_today: Calendar,
  category: Shapes,
  chat: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_right: ChevronRight,
  close: X,
  cloud_upload: UploadCloud,
  code: Code,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash2,
  deployed_code: Box,
  diamond: Gem,
  domain: Building2,
  download: Download,
  draw: PenTool,
  edit: Pencil,
  edit_note: PenLine,
  error: AlertCircle,
  expand_more: ChevronDown,
  explore: Compass,
  face: Smile,
  face_retouching_natural: Smile,
  fact_check: FileCheck,
  favorite: Heart,
  folder_open: FolderOpen,
  forum: MessageCircle,
  functions: Sigma,
  g_translate: Languages,
  graphic_eq: AudioLines,
  group: Users,
  groups: Users,
  hd: MonitorPlay,
  high_quality: ImageIcon,
  home: Home,
  hub: Network,
  insights: LineChart,
  integration_instructions: Puzzle,
  inventory_2: Package,
  lan: Network,
  language: Globe,
  local_fire_department: Flame,
  location_on: MapPin,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  manage_accounts: UserCog,
  menu: Menu,
  menu_book: BookOpen,
  mic: Mic,
  monitoring: Activity,
  movie: Clapperboard,
  music_note: Music,
  notifications: Bell,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: Wallet,
  person: User,
  person_add: UserPlus,
  person_off: UserX,
  person_remove: UserMinus,
  phone_iphone: Smartphone,
  photo_camera: Camera,
  policy: FileCheck,
  psychology: Brain,
  public: Globe,
  receipt: Receipt,
  receipt_long: ReceiptText,
  record_voice_over: MicVocal,
  remove: Minus,
  restart_alt: RotateCcw,
  rocket_launch: Rocket,
  rss_feed: Rss,
  save: Save,
  schema: Workflow,
  school: GraduationCap,
  science: FlaskConical,
  search: Search,
  search_off: SearchX,
  security: ShieldCheck,
  segment: AlignLeft,
  send: Send,
  sentiment_satisfied: Smile,
  settings: Settings,
  shield: Shield,
  shopping_cart: ShoppingCart,
  shopping_cart_checkout: ShoppingCart,
  shopping_cart_off: ShoppingBag,
  sort: ArrowUpDown,
  speed: Gauge,
  spellcheck: SpellCheck,
  star: Star,
  star_half: StarHalf,
  storefront: Store,
  style: Shirt,
  styler: Shirt,
  support_agent: Headset,
  terminal: Terminal,
  texture: Layers,
  translate: Languages,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  upload: Upload,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  videocam: Video,
  view_in_ar: Boxes,
  visibility: Eye,
  visibility_off: EyeOff,
  waving_hand: Hand,
  wb_sunny: Sun,
  workspace_premium: Award,
  schedule: Clock,
  login: LogIn,
  shield_person: ShieldCheck,
  qr_code: QrCode,
  content_copy: Copy,
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  timer_off: TimerOff,
  lock_open: LockOpen,
  mark_email_read: MailCheck,
  key: Key,
  description: FileText,
  versions: GitBranch,
  license: KeyRound,
  flag: Flag,
  circle: Circle,
  history: History,
  cancel: XCircle,
  devices: MonitorSmartphone,
  shopping_bag: ShoppingBag,
};

export type IconProps = {
  name: string;
  className?: string;
  size?: number;
  fill?: boolean;
  strokeWidth?: number;
  style?: React.CSSProperties;
};

export default function Icon({
  name,
  className = "",
  size = 20,
  fill = false,
  strokeWidth = 2,
  style,
}: IconProps) {
  const Cmp = MAP[name] || Wand2;
  return (
    <Cmp
      size={size}
      strokeWidth={strokeWidth}
      className={`inline-block shrink-0 ${className}`}
      style={style}
      fill={fill ? "currentColor" : "none"}
      aria-hidden="true"
    />
  );
}
